### ISSUE TITLE
Multi config webpack to use same template

### ISSUE THREAD

**Issue by gaje** [jantimon/html-webpack-plugin#1051]
If i have a multiple config webpack (https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations), I'm looking for a way to be able to share a common template and inject all assets built by all configurations into the same template.

Currently, the template just gets overwritten. 

Use case: I am trying to generate two separate bundles: modern and legacy (one gets loaded via `type="module"` other uses `nomodule` attribute. I need to be able to run different babel configurations against these, so i need to use separate configs - but i want both assets to be included into the same template

**Comment by goodmind** [comment]
any updates?

**Comment by Sparki2002** [comment]
I'd also appreciate such a feature

**Comment by jantimon** [comment]
I am not sure if a webpack plugin can be shared for multiple instances.  
@Sparki2002 @goodmind @gaje could you please try to find out if thats possible?

**Comment by davilima6** [comment]
I don't know if the plugin instance can be shared but discussing another approach what if `filename` is the same in multiple plugin instances but we add an `update` boolean option like [assets-webpack-plugin](https://www.npmjs.com/package/assets-webpack-plugin#updatehttps://www.npmjs.com/package/assets-webpack-plugin#update)? Do you think it'd be possible having multiple compilations incrementally writing the file?

From my tests multi-target compilation is async (at minimum you cannot guarantee the order in which they happen, even though you input them as an array, shrugs) so I'm not sure whether we'd get race conditions on write but that's the approach suggested in https://calendar.perfplanet.com/2018/doing-differential-serving-in-2019/

**Comment by davilima6** [comment]
Even though I support adding such flag, if it makes sense, I should say I'm currently outputting to different files in each config and plan to use user agent sniffing at Nginx or backend to serve a safe version because the `type="module" + nomodule` strategy is pretty limited and hits my use case. For example, the two latest versions of Edge (17-18 currently) do not handle it correctly and executes three (!) downloads: one nomodule and twice the same module one 🤦‍♂️ See: https://github.com/philipwalton/webpack-esnext-boilerplate/issues/1#issuecomment-445280691

**Comment by nishant-labs** [comment]
I would love to have this feature, specially when I need to get asset files generated by array of configuration passed to webpack.
Also it will be great if that is available in `assets` parameter in `templateParameters` function as well.

**Comment by sh-a-v** [comment]
Is there any progress?
