### ISSUE TITLE
Only generate script tags no boilerplate!

### ISSUE THREAD

**Issue by techsin** [jantimon/html-webpack-plugin#1101]
Problem: I've is that I don't want to generate the whole index.html, I want to genearte ONLY script tags with hashed filenames. Then I can include them in my files as I NEED them.

an option that prevents generation of HTML, BODY, HEAD tags. I tried providing empty html file as a template it still generate those tags.

So why?
I have an multiple apps in a website. So there isn't ONE index.js. There are multiple entry points. I have multiple views which include different js files. But I want to use hashed filenames in script src to utilize cache busting. But to do that I've to manually update filename in views. I'm trying to html webpack plugin to generate the html script tags Automatically so in my views templating system I can simply include the files that would contain script tag with correct src url. Meaning it'd have hash in the file name.

**Comment by jantimon** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on the webpack plugin itself, rather than a general forum for to get help or ask questions on your build setup.

You can ask questions on sites like Stack Overflow as we are not able to provide one-on-one support on the issue tracker.
