### ISSUE TITLE
Writing your own html?

### ISSUE THREAD

**Issue by tr1s** [jantimon/html-webpack-plugin#1122]
Sorry if this is the wrong place to ask..

How do I write my own html and have it minify into /dist? I half figured it out.. I got it minified into /dist but If I write my own html then I have `<script src="./src/index.js">` so it's connected to all my js/styles etc, but I would want it exported as `<script src="./dist/index.js">` in the html on build so when I upload to my website servers or use webpack-dev-server it'll serve the right assets and be styled.

The problem is I want to write my own html (for basic static sites) and I can't seem to wrap my head around this concept. I'd like to enjoy what Webpack 4 offers but write my own html.

**Comment by jantimon** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on the webpack plugin itself, rather than a general forum for to get help or ask questions on your build setup.

You can ask questions on sites like Stack Overflow as we are not able to provide one-on-one support on the issue tracker.

**Comment by harvey56** [comment]
@tr1s you need to add a template definition in the plugin configuration : 
`template: "path/to/your/template/template.html"`. 

You then add your script, and stuff in the template.html file.

**Comment by tr1s** [comment]
Thanks @harvey56, I had just figured this out before you mentioned it but I appreciate the comment. I added the template and imported the html in the index.js and it's all working great now.

Cheers 🙏🏽
