### ISSUE TITLE
How to process html-webpack-plugin options in required files

### ISSUE THREAD

**Issue by blachawk** [jantimon/html-webpack-plugin#1179]
* I'm working with `Webpack 4.29.4` and `html-webpack-plugin 4.0.0-beta.5` on my Windows 10 box.  My main issue is that I'm failing to process HTMLWebpackPlugin Options in required files.

* My plugin:

```js
 ...['card-single','card-double','grid-2-col-nav'].map((event) => {
      return new HTMLWebpackPlugin({
          title: ` My Page | ${event}`,
          template: `./src/views/${event}/index.html`,
          favicon: './src/images/fav_ico.ico',
          mViewPort: 'width=device-width, initial-scale=1.0',
          mFonts: 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Raleway:300,400,500|Source+Sans+Pro',
          mLayoutType: 'views',
          mWrapperClass: 'container-fluid p-0 m-0',
          memblem: './src/images/nffa_emblem_white_58x75.png',
          filename: `${event}.html`
      })
    })
```

* One of my templates (src/views/card-single/index.html):

```html
<!DOCTYPE html>
<html lang="en" class="<%= htmlWebpackPlugin.options.mLayoutType %>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="<%= htmlWebpackPlugin.options.mViewPort %>">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylsheet" href="<%= htmlWebpackPlugin.options.mFonts %>">
    <title><%= htmlWebpackPlugin.options.title %></title>
</head>
<body>
    <!--BEGIN HEADER-->
    <div class="<%= htmlWebpackPlugin.options.mWrapperClass %>">
        <%= require('html-loader!./../../partials/header.html') %>
    </div>
    <!--END HEADER-->
</body>
</html>
```
*  My partial file that is required within my template (src/partials/header.html):
```html
<header class="jumbotron bg-primary p-0 m-0 rounded-0 ffa-top-bar">
<div class="row">
  <div class="col-md-12">
    <img class="logo" src="<%= htmlWebpackPlugin.options.memblem %>" alt="">
  <div>
</div>
</header>
```
* When I attempt to render this in the browser, and check out the image path in the DOM, it *literally* says `<%= htmlWebpackPlugin.options.emblem %>` instead of a normal src image path. Why is that?  Is this fixable? or should this be a feature request for a future release?

Many many thanks in helping me think through this!

**Comment by jantimon** [comment]
The reason is that `<%= require('html-loader!./../../partials/header.html') %>` is the same as a webpack `require` inside your javascript files.

Think of it as if you would like requiring a `css` file or an `image` - they won't be executed with the same data as the file which requires them.

Furthermore you are using the html-loader to convert your `.html` file into a webpack compatible format. The html-loader does not support `<%=`.

You have to find a loader which turns your partial into a template and execute it from the main template. There are many different solutions on that depending on your loader.

I haven't tried the ejs-loader by myself but I guess the code could similar to the following:

```
<%= require('ejs-loader!./../../partials/header.html')({ htmlWebpackPlugin: htmlWebpackPlugin}) %>
```

**Comment by blachawk** [comment]
@jantimon thank you so much on providing the facts! I feel better in my position now in researching a solution. Many many thanks!
