### ISSUE TITLE
html-minifier-terser dependency has node version mismatch 

### ISSUE THREAD

**Issue by macnaughton** [jantimon/html-webpack-plugin#1313]
## Expected behaviour

Build without errors 

## Current behaviour

Received `error html-minifier-terser@5.0.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.16.0"` on one of our build machines that run node 8.  It appears `html-webpack-plugin` specifies `"engines": { "node": ">=6.9" }`, but this commit adds a dependency for html-minifier-terser that specifies >= 10:  https://github.com/jantimon/html-webpack-plugin/commit/c66766cdae3593091dee413b9c585359c24ef068 and https://github.com/DanielRuf/html-minifier-terser/blob/master/package.json#L52

## Environment

node 8.16 & html-webpack-plugin 4.0.0-beta.9+

To remedy the issue for now I've pinned html-wepback-plugin @ 4.0.0-beta.8.  I figured it's worth bringing to your attention in case others come across the issue.

**Comment by jantimon** [comment]
Thanks a lot 👍

I'll bring that to the html-minifier-terser issue board https://github.com/DanielRuf/html-minifier-terser/issues/22 

If there is no solution we will probably have to revert back to html-minifier and find a way so users can choose which minifier they want to use

**Comment by edmorley** [comment]
Node 8 is EOL in December (different cycle this time around due to OpenSSL EOL):
https://nodejs.org/en/about/releases/

...which is why a number of libraries have already started to drop support for it.

Perhaps it's worth just dropping support in html-webpack-plugin 4 too, given that date is only a month away?

**Comment by jantimon** [comment]
The recommended webpack version is 8+

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Make sure to use node &gt;= 8.9.4 when using <a href="https://twitter.com/hashtag/webpack?src=hash&amp;ref_src=twsrc%5Etfw">#webpack</a> 4 legato.<br><br>Older versions will have reduced performance, because we started using newer JS features, which are less optimized in older V8 versions.<br><br>Btw. awesome work of the v8 team regarding performance.</p>&mdash; Tobias Koppers (@wSokra) <a href="https://twitter.com/wSokra/status/967852475918274561?ref_src=twsrc%5Etfw">February 25, 2018</a></blockquote>

However to allow people keep running there systems and local environments the webpack 5 ecosystem supports node 6:

<img width="242" alt="webpack" src="https://user-images.githubusercontent.com/4113649/68657210-8f11c980-0533-11ea-8108-3985ab21c224.png">

For Webpack 5 the node version will be increased and I plan to do the same for the webpack 5 compatible html plugin:

https://github.com/webpack/webpack/blob/85145cebf3ed50014b36e76047681bbb066bbe1f/package.json#L85-L87

```
"engines": {
    "node": ">=10.13.0"
  },
```

**Comment by jantimon** [comment]
Solved thanks to @DanielRuf
