### ISSUE TITLE
Dynamically inject content ?

### ISSUE THREAD

**Issue by Legends** [jantimon/html-webpack-plugin#1325]
In my project (static multi-page app) I have a custom html template.
This template should be my layout template which should serve as a basis for all pages.
Now instead of putting everything inside this template `layout+content` and copying this for every page I want to create, I want to be able to tell the plugin to load the specified content html page.

Is this possible?

**Something like this:**
```
  new HtmlWebpackPlugin({
            template: './src/pages/layout/layout.ejs', // Reference the same layout in every html-wp plugin
            templateParameters: {
                'title': 'Index',
                'contentUrl':'../../partials/indexBody.html' // <-- something like this, to tell it to inject html into the body or another container
            },            
            inject: true,
            chunks: ['index'],
            filename: 'index.html'
        }),

  new HtmlWebpackPlugin({
            template: './src/pages/layout/layout.ejs', // Reference the same layout in every html-wp plugin
            templateParameters: {
                'title': 'About',
                'contentUrl':'../../partials/aboutBody.html' // <-- just load a different html body
            },            
            inject: true,
            chunks: ['about'],
            filename: 'about.html'
        }),
```

**The layout.ejs:**
The following does not work, I guess it first tries to parse and execute the `require` statements before injecting the template parameters
`${require('<%= contentUrl %>')}  `

So in the end I want to be able to specify a container and the respective content.html file.

**Comment by Legends** [comment]
Ok, I see there is a [partials-plugin ](https://github.com/colbyfayock/html-webpack-partials-plugin)
which uses latest beta version of `html-webpack-plugin`.

So using this plugin works fine, but now I cannot require anymore:
`   ${require('../../partials/nav.html')}`

This doesn't work anymore.

**Comment by jantimon** [comment]
The `html-webpack-plugin` is very flexible - you can use any template language see this example which uses react as a template:

[Try it on codesandbox](https://codesandbox.io/s/html-webpack-plugin--jsx-sjbcq)

The example is using typescript but of cause you can achieve the same with babel

Webpack config:

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");
const TsConfigWebpackPlugin = require("ts-config-webpack-plugin");

module.exports = {
  plugins: [
    new HtmlWebpackPlugin({
      template: "src/template.tsx"
    }),
    new TsConfigWebpackPlugin()
  ]
};
```

template.tsx
```tsx
//
// This is the entry file which is executed by the html-webpack-plugin
// during the webpack build
//

import React from "react";
import { renderToString } from "react-dom/server";

export default function() {
  return renderToString(
    <html>
      <head />
      <body>
        <div id="main">
        </div>
      </body>
    </html>
  );
}
```

For other template languages it works the same way - just add a loader to your webpack config and it will be used for your template file.

**Comment by Legends** [comment]
Perhaps you didn't get me or probably I didn't get you :-)

I am using `html-loader`.

My `layout.ejs` template file, is a simple html document (no JavaScript, exports, imports, etc. inside).
I usually put `${require('../../partials/nav.html')}` in a certain section of the html template to import partials (another.html), this template is then parsed by your plugin and the partial gets injected, but with latest beta version of `html-webpack-plugin` this does not work anymore.

Importing from a tsx template is not a problem as it is JavaScript, but my template is pure html, where I put the `require` statement from above.
And inside of an html file the require statement is just text and does nothing on its own.

The html import is done by your plugin.

Aaaaa I hope you understand me better now ;-)

**Comment by Legends** [comment]
This all works fine with the latest release version.

But now I want to be able to tell the `HtmlWebpackPlugin` which html partial to load for the body.
The layout.ejs template **is the same for all**.
Example:
For the generated` index.html` page I want it to render a `index-body.html` inside of its body.
For the generated` about.html` page I want it to render a `about-body.html` inside of its body.

I cannot require a body.html inside of the layout template, the template is for all pages the same.
```
 new HtmlWebpackPlugin({
            // template: './src/pages/home/layout.html',
            template: './src/pages/layout/layout.ejs',
            templateParameters: {
                'title': 'Index'
            },
            inject: true,
            chunks: ['index'],
            filename: 'index.html'
        }),
        new HtmlWebpackPlugin({
            // template: './src/pages/home/layout.html',
            template: './src/pages/layout/layout.ejs',
            templateParameters: {
                'title': 'About'
            },
            inject: true,
            chunks: ['about'],
            filename: 'about.html'
        }),
```

**Comment by Legends** [comment]
Forget about everything.
To make it simple, can we make `require` work again in latest beta version?

**layout.ejs**
`${require('../../partials/nav.html')} `

**Comment by jantimon** [comment]
As I tried to show with the tsx example you can use any loader.

What you can do for example:

Add the ejs-loader to your project and have the following about.html:

```
<%= require("./head.ejs") %>
about
<%= require("./footer.ejs") %>
```

**Comment by colbyfayock** [comment]
@jantimon so to explain the use case a little bit here - the plugin i set up to work based on html-webpack-plugin injects "partials" into the html pipeline. the big use case here is that you won't have to maintain a template file, instead, you simply define a partial file and where you want it to be added. this is particularly useful for something like a React app, where instead of having to redefine all of the import bits and pieces of the template itself requiring someone to maintain that through potential changes, they simply have to define this 1 partial with the required code that gets plugged in through the compile chain

ive been trying to figure out though how to get this running in v4 and have been struggling with it a bit. im not super well versed in the webpack ecosystem, but previously, i was successfully able to simple string replace in the partial given the location and some regex magic which would allow the html-webpack-plugin to compile it as i needed it. now, i can't seem to find a good spot to plug that into. 

i found in `afterTemplateExecution` there's a nice `headTags` and `bodyTags` that ive considered utilizing, but it seems like it doesn't include ALL potential body and head tags that might process through the pipeline, which could impact the loading order for things like adding a particular tag, like some extra JS-y import, at the end of the file, as well as i can't prioritize the order that the head would load in, such as loading google tag manager at the very top of the head behind the charset

any recommendations on a direction i could go here? i was considering trying to hook into some of the utils you make available, but when i was digging in, i couldn't really find anything public that would help me here. for instance, if there was a method publicly available that let me "compile" each individual partial file, effectively running your processing on the file resolving things like `${require('<%= contentUrl %>')}`, that would make of a nice way for me to hook into it.

you can see some of the use cases im providing here: https://github.com/colbyfayock/html-webpack-partials-plugin/tree/master/examples

any thoughts on this?

**Comment by colbyfayock** [comment]
and just to clarify, the injection process is working currently as expected, however, it doesn't resolve the requires

**Comment by Legends** [comment]
Ok, I get your approach, it's like:

```
<%= require("./head.ejs") %>
               index // <-- page content
<%= require("./footer.ejs") %>
<hr/>
<%= require("./head.ejs") %>
               about // <-- page content
<%= require("./footer.ejs") %>
<hr/>
<%= require("./head.ejs") %>
              contact // <-- page content
<%= require("./footer.ejs") %>
```

I like to keep it `DRY`. We have to repeatedly require `head` and `footer` in every page with this approach.

**What I would like to be able to do:**
For every page I want to create, I instantiate `HtmlWebpackPlugin` and specify a `composition` property where one could specify objects as key-value pairs where the key is a tag/selector (container where the resource gets injected) and the value is the resource to be injected.

**Like this for example:**
 new HtmlWebpackPlugin({       
            template: './src/pages/layout/layout.ejs',
            templateParameters: {
                'title': 'Index'
            },
            composition:[
                {'main' : './src/pages/about/about-body.html'},  // body gets injected into main tag
                {'aside' : './src/pages/about/navbar.html',}  // navbar into aside tag
            ],
            inject: true,
            chunks: ['index'],
            filename: 'index.html'
        }),

**Question is:** 
Is this already possible with `html-webpack-plugin` or needs to be implemented as a separate plugin?
If this should be a separate plugin, which webpack-hook would fit best to inject the resources into the template, especially when considering resources that also can contain `require` calls in their html, in order for them to get processed correctly?

**Comment by Legends** [comment]
Closed in favor of [feature request](https://github.com/jantimon/html-webpack-plugin/issues/1330)
