### ISSUE TITLE
Question: Is there a possibility to fill parts of a template with "external" content?

### ISSUE THREAD

**Issue by stupkad** [jantimon/html-webpack-plugin#1558]
Hi there,

I have successfully set up a webpack project (html, typescript, scss) to create a static html site as one pager with styles and logic. So far, so good. The htmlwebpackplugin is currently used to inject the hashed script and styles into the html.

Actually my template consists everthing, including the content. Now I am looking for a smart and easy way to extract the context (which are words and also longer text/blocks) into external (markdown) files. See https://www.minaxus.at/ to get an idea which texts should be replaced.

Hugo/Jeklyy is ways too complex for my usecase. Using a simple cms (e.g. kirbycms) would be an option, but would result in decreased performance and add the need for php at the server side when hostet.

Is there a possibility to do this with one of the temlate engines, or would I have to write my own plugin for doing that?

Thanks a lot, 
Dietmar

**Comment by jantimon** [comment]
There are many different solutions depending on your preferred template language

By default the html-webpack-plugin is using the underscore template loader which is very similar to ejs

For example 

```js
new HtmlWebpackPlugin({ template: 'index.ejs' })```

That way your template can require and execute any javascript e.g.:

index.ejs
```
<html>
<body>
<%= require("./demo.js").myContent() %>
</body>
</html>
```

demo.js
```js
export function myContent() {
  return '<h1>hello world</h1>'
}
```

Webpack is a quite powerful tool which is able to convert a lot of template languages like twig or markdown to javascript using loaders. So instead of writing your content in a `.js` file you write it for example in a `.md` file and use a markdown loader in your webpack config.  
The example from above could then look like this:

index.ejs
```
<html>
<body>
<%= require("./demo.md") %>
</body>
</html>
```

demo.md
```md
# hello word
```

The html-webpack-plugin will also use your loader configuration for the file you specific as template - so if you set up a `.md` loader you could directly use it in your template:


```js
new HtmlWebpackPlugin({ template: 'index.md' })```


index.md
```md
<html>
<body>
# hello word
</body>
</html>
```

I hope that helps

please note that right now webpack 5 has some limitations for the child compiler so some of these features might work only in webpack 4 for now

**Comment by stupkad** [comment]
Hi Jan, thanks for this great summary, it helps me a lot to take the next steps!
Regards,
Dietmar
