### ISSUE TITLE
types "Compilation" in webpack shoud be compilation.Compilation

### ISSUE THREAD

**Issue by zhangxuyang-web** [jantimon/html-webpack-plugin#1595]
## Current behaviour 💣
`import { Compiler, Compilation } from "webpack";` in types.d.ts

## Expected behaviour ☀️
should be import { Compiler, compilation.Compilation } from "webpack";

**Comment by jantimon** [comment]
why?

**Comment by astorije** [comment]
I suspect @zhangxuyang-web got an error similar to the following one I got:

```
node_modules/html-webpack-plugin/typings.d.ts:2:20 - error TS2724: '"../@types/webpack"' has no exported member named 'Compilation'. Did you mean 'compilation'?

2 import { Compiler, Compilation } from "webpack";
                     ~~~~~~~~~~~

  node_modules/@types/webpack/index.d.ts:716:15
    716     namespace compilation {
                      ~~~~~~~~~~~
    'compilation' is declared here.
```

However, I don't expect this to actually come from `html-webpack-plugin` (and the suggestion in issue description is not valid JS/TS), but rather from another Webpack plugin importing `@types/webpack` and therefore forcing `html-webpack-plugin` to use the typings from `@types/webpack` instead of `webpack` itself.

When I look at my `yarn.lock`, I see the following:

```
"@types/webpack-dev-server@3.11.1":
  version "3.11.1"
  resolved "https://..."
  integrity sha512-...
  dependencies:
    "@types/connect-history-api-fallback" "*"
    "@types/express" "*"
    "@types/http-proxy-middleware" "*"
    "@types/serve-static" "*"
    "@types/webpack" "*"

[...]

html-webpack-plugin@5.0.0:
  version "5.0.0"
  resolved "https://..."
  integrity sha512-...
  dependencies:
    "@types/html-minifier-terser" "^5.0.0"
    html-minifier-terser "^5.0.1"
    loader-utils "^2.0.0"
    lodash "^4.17.20"
    pretty-error "^2.1.1"
    tapable "^2.0.0"
```

So in my case, I suspect the issue from the `webpack-dev-server` plugin instead.
@zhangxuyang-web, you're probably encountering a similar problem with another plugin, can you confirm?

**Comment by jantimon** [comment]
wow thanks a lot @astorije for the insides 👍

you are right - webpack 5 ships with its own typings now so `@types/webpack` is not needed anymore

using `@types/webpack` together with webpack 5 will cause issues - maybe we can also add a PR for `@types/webpack` to use the typings from webpack directly and deprecate the package
