### ISSUE TITLE
can't parse <%% tag in ejs file

### ISSUE THREAD

**Issue by allenlongbaobao** [jantimon/html-webpack-plugin#1648]
## Current behaviour 💣
when i use `<%%` tag in ejs file，the compile process will break with error below:
![image](https://user-images.githubusercontent.com/3255868/119978932-d31cd000-bfec-11eb-9aad-6f4c36d6708e.png)

## Expected behaviour ☀️

it's confused when i use ejs but some tag is not support, i think it's not ejs's problem and i want to make sure why it happened and how to solve it

any one helps?

**Comment by MakarovAV** [comment]
I encountered the same problem and can offer workarounds that worked for me.

The question is why you need "<%" literal in the output?

1. The first scenario - you need this literal to be visible by a human/consumed by javascript.
In this case, you can get away by replacing one of the symbols with a corresponding HTML entity/Unicode string literal.
The escaped string does not seem to be recognized by the parser as template construction.

Specifically, write '&lt;%' instead of '<%' in the HTML. (< symbol replaced)
''<\u0025" in js (% symbol replaced by its hex representation)

2. The second scenario is the issue that led me here and took me some time to find a workaround. 

I needed to generate not an HTML but a JSP page containing a couple of simple JSP includes.
Generally speaking, it is not a valid HTML but it is a template consumed by a server-side template engine. Yep, the architecture sucks, but real-world problems, you know.

JSP has a lot of constructions with <%, If I escaped them, they would have not been recognized by the JSP template engine.
Turns out JSP has an alternative way to describe its includes.
For example I can use `<jsp:expression>someJavaCode()</jsp:expression>` instead of `<%= someJavaCode() %>`. No <%, works like a charm.

Generally speaking, if you want to emit something consumed by another templating engine, you might try to find a  solution by better understanding what that other templating engine can accept.

Hope it helps.
