### ISSUE TITLE
Custom Insertion Position example is misleading

### ISSUE THREAD

**Issue by happycollision** [jantimon/html-webpack-plugin#1665]
## Current behaviour 💣

Your own example of [custom insertion position](https://github.com/jantimon/html-webpack-plugin/tree/e5036c807184b76c915fc71917d29e76e1807c05/examples/custom-insertion-position) seems to have failed.

All the tags are placed in the head:

https://github.com/jantimon/html-webpack-plugin/blob/e5036c807184b76c915fc71917d29e76e1807c05/examples/custom-insertion-position/dist/webpack-5/index.html#L3-L6

And none are in the spot that is called out specifically:

https://github.com/jantimon/html-webpack-plugin/blob/e5036c807184b76c915fc71917d29e76e1807c05/examples/custom-insertion-position/dist/webpack-5/index.html#L7-L11

## Expected behaviour ☀️

I'd expect the example dist output to place one or more tags where it says it should.

Now, I think this is because the bundle script is actually part of the head tags, which is fine. But the example seems to be calling out something that doesn't exist.

### Reproduction Example 👾

Just look at the repo as it is today.

## Environment 🖥

The env you built the repo with. ;-)

**Comment by jantimon** [comment]
You are right this is confusing - with version 5 of the html-webpack-plugin the way javascript is load has been changed by default.

Instead of injecting scripts at the end of the body element the defer attribute is used: `<script defer src="bundle.js"></script>`

This new technique allows the browser to start downloading and parsing your javascript earlier and in parallel.

You can disable this feature with the following option: `scriptLoading: 'blocking'`
