### ISSUE TITLE
Allowing scriptLoading type async in addition to defer

### ISSUE THREAD

**Issue by AirBorne04** [jantimon/html-webpack-plugin#1694]
**Is your feature request related to a problem? Please describe.**
Loading a script with `defer` is executing the script as soon as it is loaded and therefore might interrupt other parsing. Adding the `async` attribute instead is allowing the browser to decide when to execute the script and therefore allows a better control over the importance of the script execution by the developer.

**Describe the solution you'd like**
Add a `scriptLoading` option for `async` to control the described behaviour better.

**Describe alternatives you've considered**
Currently i am using a deprecated Webpack plugin just to achieve this (script-ext-html-webpack-plugin).

**Additional context**
There is currently a PR #1672 open for adding `module` as an option, adding `async` should be an easy addition to that PR.

**Comment by nihgwu** [comment]
https://github.com/reactwg/react-18/discussions/114

**Comment by jantimon** [comment]
@nihgwu that's great feedback - thanks a lot :)
it sounds like that reacts framework limitations disallow common best practices..  
so we should definitely add `async` to html-webpack-plugin..

my only concern is that some users might use `async` for non react apps..

I'll take a closer look how we can integrate #1672

**Comment by guanzo** [comment]
> Could you explain your scenario a little bit more to help me understand why you don't want to wait for the DOM?

`async` hits the sweet spot between performance and UX. See this [post](https://stackoverflow.com/a/39711009/2498782) for a visual explanation

I want to run some code ASAP, but not so much that the script download should block the DOM. e.g. installing a service worker, establishing network connections. The code doesn't depend on the DOM so it doesn't need to wait for it. My code is published as a 3rd party script, so the user will add it to their HTML. I can't just hardcode performance critical code into the HTML as I don't control it, otherwise I would. 

The ideal scenario for me is an `async` <script> that gets placed in the `<head>`. That way the script loading is initiated early and executes as soon as its downloaded. Using `defer` isn't optimal for my use case.

**Comment by jantimon** [comment]
@guanzo I guess that's really the case for async but unfortunately a  real edge case for regular webpack users.. 

What you can do is to change the script loading with a hook to async or turn auto injection off
