### ISSUE TITLE
Include lazy-loaded chunks in `htmlWebpackPlugin.files` for preload

### ISSUE THREAD

**Issue by yyx990803** [jantimon/html-webpack-plugin#563]
This is a feature request.

Currently lazy-loaded chunks are simply ignored; however it would be useful to expose them in `htmlWebpackPlugin.files`, maybe as `htmlWebpackPlugin.files.asyncChunks` so that we can use it to populate `<link rel="preload">` hints in the HTML.

- https://developers.google.com/web/updates/2016/03/link-rel-preload
- https://www.w3.org/TR/preload/

I'd be happy to make a PR for this if this sounds reasonable.

**Comment by jantimon** [comment]
Would be nice in combination with https://github.com/jantimon/resource-hints-webpack-plugin

**Comment by yyx990803** [comment]
@jantimon ohh nice, didn't know that one existed! 👍

**Comment by developit** [comment]
@yyx990803 I found a way to do this:
https://github.com/developit/preact-www/blob/412c87b00845a981ce54e902742b451584eee043/src/index.html#L15-L21

**Comment by yyx990803** [comment]
@developit ah sweet, thanks for sharing!

**Comment by developit** [comment]
Might be nice to get those things added (as an option) to html-webpack-template.

**Comment by jantimon** [comment]
@developit please add a pr for
https://github.com/jantimon/resource-hints-webpack-plugin
or take a look at 
https://github.com/GoogleChrome/preload-webpack-plugin

**Comment by borisirota** [comment]
Hi @jantimon I have a similar use case but with a twist and it seems to me the right place to explain it and ask if `html-webpack-plugin` is the right place for having this kind of functionality out of the box.

I'm building fully static SPA with react and generating all the pages on build time as well (multiple `html-webpack-plugin` instances). It works that the skeleton (i.e. header, footer, etc.) have all the initial chunks (i.e. index.js, vendors.js, etc.) which being synchronously loaded on every page and then the relevant chunk (i.e. settings_page.js) is being asynchronously requested once going to the relevant page and in the meanwhile there is some loading indicator.

With this approach where I serve complete html for every page, the result is that when react takes control on the client (after onload event), it still doesn't have the relevant chunk for the current page => it makes a request to the server for this chunk and meanwhile replaces the html with the loading indicator => which defeats the purpose of rendering at build time and serving complete html.

What I really need is that in addition to initial chunks, every page will include in it's html link to the relevant chunk of the current page as well (which will exist on onload event).

In order to support that, I added to options the asyncChunks field and in every instance of the 
`html-webpack-plugin` I set this array to include the chunk name of the current page.

In addition I built this plugin:
```
function InjectAsyncChunksWebpackPlugin () {}
InjectAsyncChunksWebpackPlugin.prototype.apply = function (compiler) {
  compiler.plugin('compilation', function (compilation) {
    compilation.plugin('html-webpack-plugin-alter-chunks', function (chunks, htmlPluginData) {
      var asyncChunks = compilation.getStats().toJson().chunks.filter((chunk) => htmlPluginData.plugin.options.asyncChunks.indexOf(chunk.names[0]) !== -1)
      if (asyncChunks.length) chunks = chunks.concat(asyncChunks)
      return chunks
    })
  })
}
module.exports = InjectAsyncChunksWebpackPlugin
```

As you can see, this plugin has nothing to do with resource hints and its purpose is to extend the initial chunks to support use cases like serving SPA which being fully rendered at build time for maximum performance in fully static apps (pretty common pattern from my point of view).

Do you think `html-webpack-plugin` should support it out of the box ?
