### ISSUE TITLE
How does it know the hashed file names to use?

### ISSUE THREAD

**Issue by dland512** [jantimon/html-webpack-plugin#615]
Given that the output file names are going to be different on every compilation, now does this thing know what names to inject into the resulting html file?

**Comment by wosevision** [comment]
From this repository's readme.md:

> You can use the lodash syntax out of the box. If the inject feature doesn't fit your needs and you want full control over the asset placement use the default template of the html-webpack-template project as a starting point for writing your own.
> 
> The following variables are available in the template:
> 
> htmlWebpackPlugin: data specific to this plugin
> 
> htmlWebpackPlugin.files: a massaged representation of the assetsByChunkName attribute of webpack's stats object. It contains a mapping from entry point name to the bundle filename, eg:
> 
> ...
> 
> webpack: the webpack stats object. Note that this is the stats object as it was at the time the HTML template was emitted and as such may not have the full set of stats that are available after the wepback run is complete.
> 
> webpackConfig: the webpack configuration that was used for this compilation. This can be used, for example, to get the publicPath (webpackConfig.output.publicPath).

The hashed filenames are retrieved by the plugin through the usual Webpack methods and injected into the HTML – knowing what those file names are going to be is just one of the things this plugin does.

I'd recommend asking these questions on StackOverflow instead of filing them as issues with the plugin. Often you'll end up [finding the answer to your question in someone else's](http://stackoverflow.com/questions/38080915/what-does-the-html-webpack-plugin-mean-when-it-says-hash-in-the-filename).

Also, check out the Webpack docs for a further breakdown of how those filenames are generated and where to retrieve them:
[https://webpack.js.org/configuration/output/](https://webpack.js.org/configuration/output/)
