### ISSUE TITLE
What if I need to build HTML content using the chunks data?

### ISSUE THREAD

**Issue by VictorQueiroz** [jantimon/html-webpack-plugin#625]
What if I don't want `html-webpack-plugin` to generate the HTML for me? Would be great if we have an option like:

```js
new HtmlWebpackPlugin({
    output: (chunksData) => {
        fs.writeFileSync('./public/index.html', nunjucks.renderString(template, chunksData));
    }
})
```

**Comment by mastilver** [comment]
After some research, there is two nunjucks loaders:
- https://www.npmjs.com/package/nunjucks-loader
- https://www.npmjs.com/package/nunjucks-html-loader

The first one doesn't return a function, it returns a `obj` with the method `render` on it
The second doesn't take parameters

The best way for `html-webpack-plugin` to handle nunjucks is to ask the author of https://www.npmjs.com/package/nunjucks-loader to return a `function` rather than an object

Overwise you have many other engines available: https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md

**Comment by mastilver** [comment]
Just noticed there is already an open issue related to that: https://github.com/at0g/nunjucks-loader/issues/35

**Comment by VictorQueiroz** [comment]
Thank you for your answer. But the point is to handle it without having to depent of any template options. I mean in my case I need to add css file path that is not generated using Webpack, so it's not a part of entry point and would be great if that option is allowed by the module.

**Comment by mastilver** [comment]
Oh, I see, I misunderstood you.

So to be clear, you want in the same html file you want:
- static css (almost never change)
- generated assets from webpack

I'm afraid you will have to use a template

Here the template you could use:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My app</title>
        <meta charset="UTF-8">
        <link href="my-static-style.css" rel="stylesheet">
    </head>
    <body>
    </body>
</html>
```

The rest of your css will be added in the `head` **alongside** your static css
Your javascript will be placed in the `body`

**Comment by mastilver** [comment]
You could also use https://github.com/SimenB/add-asset-html-webpack-plugin or https://github.com/jharris4/html-webpack-include-assets-plugin

**Comment by aendrew** [comment]
Anyone needing to use Nunjucks with `html-webpack-plugin`, I've managed to do so with the instructions here: https://github.com/at0g/nunjucks-loader/issues/35#issuecomment-324297477
