### ISSUE TITLE
cannot use EJS tag "<%-" to output the unescaped value into the template.

### ISSUE THREAD

**Issue by mingxian** [jantimon/html-webpack-plugin#734]
## Description

cannot use EJS tag "<%-" to ouput the unescaped value into the template.

### Config

Copy the relevant section from `webpack.config.js`:

```js
module.exports = {
  plugins: [
    new HtmlWebpackPlugin(
          filename: path.resolve(__dirname, './index.html',
          template: path.resolve(__dirname, './template.ejs'),
          cache: false,
          inject: false 
   ),
    ...
  ]
}
```

Copy your template file:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
<pre>
<%-
  '{"version" : "1.0.0"}'
%>
</pre>
    </body>
</html>
```

## Output 
```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
<pre>
{&quot;version&quot; : &quot;1.0.0&quot;}
</pre>
    </body>
</html>
```

## Expected
```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
<pre>
{"version" : "1.0.0"}
</pre>
    </body>
</html>
```
## Environment

Node.js v6.11.0
darwin 16.6.0
npm 3.10.10
webpack 3.2.0
html-webpack-plugin 2.29.0

**Comment by iamricky** [comment]
I've been struggling a similar issue and have uncovered a number "quirks," in the process.  I'm using `"html-webpack-plugin": "^2.29.0"` with `"webpack": "^3.1.0"` and everything (_literally_, everything) breaks. It's a shame because I have another app that runs `"webpack": "1.x"` with `"html-webpack-plugin": "^2.28.0"` which works fine.

Honestly, if you value your time, I would recommend using another plugin (e.g. [html-webpack-template](https://github.com/jaketrent/html-webpack-template)). `html-webpack-plugin` has become too unreliable and unpredictable to be used in production (if at all).

**Comment by mastilver** [comment]
Use this template

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
<pre>
<%=
  '{"version" : "1.0.0"}'
%>
</pre>
    </body>
</html>
```

Notice `<%=` vs `<%-`
