### ISSUE TITLE
Using path aliases with EJS templates in html-webpack-plugin

### ISSUE THREAD

**Issue by EddyVinck** [jantimon/html-webpack-plugin#975]
## Expected behaviour

I expected to be able to use Webpack's path aliases within my templates, but I can't figure out how. I looked in the documentation and in other threads but I haven't been able to find a solution.

## Current behaviour

Compilation errors

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v9.9.0
win32 10.0.16299
npm --version 6.0.0
html-webpack-plugin@3.1.0
webpack 4.8.3
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
resolve: {
	alias: {
		fontello: path.resolve(__dirname, 'src/assets/fonts/icons/fontello-icons'),
		img: path.resolve(__dirname, 'src/assets/img')				
		}
	},
```

Copy your template file if it is part of this issue:

```html
<!-- does not work -->
<img src="<%= require('~img/some-image.jpg') %>" alt="Thanks for the help">

<!-- works, but less ideal when paths get more complicated -->
<img src="<%= require('../img/tut-copy-document.jpg') %>">
```

**Comment by jantimon** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on the webpack plugin itself, rather than a general forum for to get help or ask questions on your build setup.

You can ask questions on sites like Stack Overflow. We are not able to provide one-on-one support on the issue tracker.  Thanks
